FROM node:16-alpine AS development
ENV NODE_ENV development

WORKDIR /app
# Copy app files
COPY package.json .
COPY package-lock.json .
COPY . .

RUN npm ci 

EXPOSE 3000

CMD [ "npm", "run", "start" ]